### ISSUE TITLE
st type:img width height 无效 无法设置图片大小

### ISSUE THREAD

**Issue by hennychen** [ng-alain/ng-alain#1040]
- ng-alain version: ^7.2.0
- Angular version: ^7.2.12

## 【必填项】重现链接，Reproduction link
https://stackblitz.com/run?file=src/app/app.component.ts

## 重现步骤，Steps to reproduce
st 表格 type：img  设置列表中图片大小无效

**Comment by cipchk** [comment]
duplicated of #1018

**Comment by cipchk** [comment]
img 当前为固定大小，若需要调整某个大小可以自行写 less，例如：

```less
:host st img {
  max-height: 64px;
  max-width: 64px;
}
```

> 若想全局修改，可以覆盖 `@nz-table-img-max-height`、`@nz-table-img-max-width` 两个样式参数值。
