### ISSUE TITLE
st 的样式影响到单独使用 nz-table

### ISSUE THREAD

**Issue by s97712** [ng-alain/ng-alain#1078]
- ng-alain version: least
- Angular version: least

## 【必填项】重现链接，Reproduction link

st 的样式连同 nz-table 也一起影响了，单独使用 nz-table 会出现 st 的部分样式
```css
/* 以下样式为 st 的样式，但却作用于所有 nz-table */
@media screen and (max-width: 767px)
.ant-table-tbody > tr > td {
    width: 100%;
    display: flex;
    align-items: center;
    text-align: left !important;
    border-bottom: none; 
    padding: 8px 8px; 
}
```
