### ISSUE TITLE
st thead ---Can you hide? 

### ISSUE THREAD

**Issue by hennychen** [ng-alain/ng-alain#1080]
Can you hide 'st'  thead ?
add st thead is show property.
\\

大神 st 可否增加 隐藏 thead 表头的属性

**Comment by cipchk** [comment]
使用一个简单的 css 就可以了，例如：

```less
# styles/index.less
.hide-st-title {
  .ant-table-thead {
    display: none;
  }
}
```

使用：

```html
<st class="hide-st-title"></st>
```
