### ISSUE TITLE
SFButton submit按钮 不能设置 nzBlock 效果，即占满24格

### ISSUE THREAD

**Issue by FoolEdward** [ng-alain/ng-alain#1222]
🚨 Issues 是用于BUG、Feature、进度追踪 🚨
🚨 The issue tracker is not for questions 🚨

如果有任何问题，可在以下方式获得答案：

- https://ng-alain.com/
- QQ Group：316911865
- https://segmentfault.com/t/ng-alain

**Comment by cipchk** [comment]
暂时不会考虑该功能，若有需求请自行增加在 `styles/index.less` 增加（它将针对所有 `sf` 有效）：

```less
.sf-btns {
  .ant-btn {
    width: 100%;
  }
  .ant-btn-default {
    margin-left: 0;
  }
}
```
