### ISSUE TITLE
reuse-tab内部的Tabs和ng-zorro的Tabs样式不匹配

### ISSUE THREAD

**Issue by KellenHe** [ng-alain/ng-alain#1779]
- ng-alain version: 9.5.1
- Angular version: 9.1.11

## 【必填项】重现链接，Reproduction link
 
![image](https://user-images.githubusercontent.com/9713892/87912285-ae3c0000-ca9f-11ea-8aea-df6aad373f7e.png)

## 重现步骤，Steps to reproduce
在9.X中，tabs的下划线宽度和字体宽度一样，但是reuse-tab的宽度还是超过字体宽度。

**Comment by cipchk** [comment]
你可以在 `styles.less` 下增加一段来覆盖：

```less
.reuse-tab__line .ant-tabs-nav .ant-tabs-tab .reuse-tab__name {
  padding-left: 0;
  padding-right: 0;
}
```
