### ISSUE TITLE
preloader在chrome84里并没有移除或隐藏

### ISSUE THREAD

**Issue by liwei511** [ng-alain/ng-alain#1908]
``` javascript
  function remove(): void {
    // preloader value null when running --hmr
    if (!preloader) return;
    preloader.addEventListener('transitionend', () => {
      preloader.className = 'preloader-hidden';
    });
    preloader.className += ' preloader-hidden-add preloader-hidden-add-active';
  }
```
并没有为preloader设置上class:preloader-hidden

**Comment by liwei511** [comment]
```css
    .preloader {
      position: fixed;
      top: 0;
      left: 0;
      width: 100%;
      height: 100%;
      overflow: hidden;
      background: #49a9ee;
      z-index: 9999;
      transition: opacity .65s
    }
```

找到原因了， 我把transition删了。 抱歉打扰
