### ISSUE TITLE
st第一列是checkbox情况，小屏幕显示异常。

### ISSUE THREAD

**Issue by zegnanxi** [ng-alain/ng-alain#1962]
### Reproduction link
[https://stackblitz.com/edit/angular-6tubx6?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-6tubx6?file=src/app/app.component.ts)

### Steps to reproduce
缩小屏幕到xs。

### What is expected?
当xs之后，布满整个屏幕。

### What is actually happening?
当xs之后，显示异常，没能布满整个屏幕

| Environment | Info |
|---|---|
| ng-alain | 11.8.0 |
| Browser | chrome |

---
11.7.1正常，升级11.8.0后出现此bug。

**Comment by cipchk** [comment]
临时解决办法，在 `styles.less` 加入：

```less
@media screen and (max-width: 767px)
.ant-table-rep .ant-table table {
    width: 100% !important;
}
```
