### ISSUE TITLE
移除主题中的代码块样式

### ISSUE THREAD

**Issue by yedajiang44** [ng-alain/ng-alain#2019]
希望将主题中的`code`标签样式移除，否则会影响第三方代码高亮插件的显示效果
主题自带样式
```css
code {
  margin: 0 4px;
  padding: 2px 4px;
  font-size: 90%;
  background-color: @code-bg;
  border: 1px solid @code-border-color;
  border-radius: @border-radius-base;
}
```

临时解决方案：在`src/style.less`中覆盖主题中`code`标签样式
```css
code {
  margin: 0 !important;
  padding: 0 !important;
  background: none !important;
  border: none !important;
  border-radius: 0 !important;
}
```
