### ISSUE TITLE
MS主题菜单优化

### ISSUE THREAD

**Issue by Anberm** [ng-alain/ng-alain#2035]
### Reproduction link
[https://stackblitz.com/run?file=src/app/app.component.ts](https://stackblitz.com/run?file=src/app/app.component.ts)

### Steps to reproduce
![sidebar](https://user-images.githubusercontent.com/34148806/126524279-9bf88b53-306e-436a-9a96-40b0ac89f26f.gif)

看gif
1.点开左侧菜单
2.开始拖放
3.完成拖放
4.图标位置偏移

偏移原因在于这段代码
```less
.alain-ms__sidebar-product-quick {
    width: calc(100% + 20px); 
}
```
如果想要隐藏滚动条，这样处理是否更合适
```less
  // 快捷菜单
 &-quick {
        position: relative;
        // 隐藏滚动条
        // width: calc(100% + 20px);
        height: calc(100% - 48px);
        margin: 0;
        padding: 0;
        overflow-y: auto;
        list-style: none;
        -ms-overflow-style: none;
        scrollbar-width: none;
        &::-webkit-scrollbar {
          display: none;
        }
      }
```
另外，拖动应该做些样式优化，建议如下
```less
      //避免重叠显示
      &.cdk-drag-placeholder {
        opacity: 0;
      }
      //避免触发hover样式
      .cdk-drop-list-dragging &:not(.cdk-drag-placeholder) &-toolbar {
        display: none !important;
      }

```

还有就是菜单响应速度，感觉上0.3s有点慢了，改成0.2s顺畅很多
```less
transition-delay: 0.2s;
```

### What is expected?
正常显示

### What is actually happening?
位置偏移

| Environment | Info |
|---|---|
| ng-alain | 12.0.0 |
| Browser | Google Chrome |
