### ISSUE TITLE
补充菜单的api

### ISSUE THREAD

**Issue by akliyiping** [ng-alain/ng-alain#700]
![image](https://user-images.githubusercontent.com/11307344/46244499-42902b00-c412-11e8-920e-1183bf830fdb.png)
需求：
只让‘分析页‘高亮，
不让父菜单’仪表盘‘高亮
现状：
目前的api不支持这个需求

**Comment by cipchk** [comment]
不会支持，可以自己写 css 覆盖。

```less
.sidebar-nav {
  &__selected > a {
    color: inherit;
  }
  &__item .sidebar-nav__item.sidebar-nav__selected {
    color: #1890ff;
  }
}
```
