### ISSUE TITLE
how to change left menu or menuitem selected color in style?

### ISSUE THREAD

**Issue by AiHaibara** [ng-alain/ng-alain#895]
how to change left menu or menuitem selected background color in less style?
sidebar.component.less
I Add this but can't work
```
.sidebar-nav__selected {
            border-left-color: #13c2c2;
            background-color: #343434;
}
```

**Comment by cipchk** [comment]
You can using `@alain-default-aside-nav-selected-text-color` less parameter, pls refer to [document](https://ng-alain.com/theme/default/en)

**Comment by AiHaibara** [comment]
@cipchk Thank you, It works.

**Comment by AiHaibara** [comment]
> parameter
@cipchk 
@alain-default-aside-nav-selected-bg can change background current group,
but how to change the background current selected item?

**Comment by cipchk** [comment]
When you want to override undefined LESS parameters, it's best via s`rc/styles/theme.less`, like this:

```less
// theme.less

.sidebar-nav__selected {
            border-left-color: #13c2c2;
            background-color: #343434;
}
```
